name: My first action workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: List and Read File
              run: |
                echo "My first Github Action Jobs"
                ls -ltra
                cat README.md

            - name: Generate ASCII Artwork
              run: cowsays -f dragon "Run for cover, I am a dragon ... RAWR" >> dragon.txt